from __future__ import annotations

from pathlib import Path

from .models import CheckResult


def remediation_filename(target_platform: str) -> str:
    return {
        "linux": "remediate_linux.sh",
        "macos": "remediate_macos.sh",
        "windows": "remediate_windows.ps1",
    }[target_platform]


def render_remediation_script(target_platform: str, failed_results: list[CheckResult]) -> str:
    if target_platform == "windows":
        lines = [
            "$ErrorActionPreference = 'Stop'",
            "",
            "# Generated by security-audit-tool. Review before execution.",
        ]
        for result in failed_results:
            lines.append("")
            lines.append(f"# {result.rule_id}")
            lines.extend(result.remediation)
        return "\n".join(lines) + "\n"

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by security-audit-tool. Review before execution.",
    ]
    for result in failed_results:
        lines.append("")
        lines.append(f"# {result.rule_id}")
        lines.extend(result.remediation)
    return "\n".join(lines) + "\n"


def write_remediation_script(output_dir: Path, target_platform: str, failed_results: list[CheckResult]) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / remediation_filename(target_platform)
    path.write_text(render_remediation_script(target_platform, failed_results), encoding="utf-8")
    if target_platform != "windows":
        path.chmod(0o750)
    return path
